drop table if exists app_user cascade;
drop table if exists project cascade;
drop table if exists user_per_project;
drop table if exists parsing_job cascade;
drop table if exists search_by_text;
drop table if exists parsing_link;
drop table if exists feedback_object;
drop table if exists statistical_report cascade;
drop table if exists ai_report;
drop table if exists card_object cascade;
drop table if exists liked_cards;
drop table if exists stars_count;
drop table if exists feedback_states_count;
drop table if exists top_5_words;
drop type if exists role_enum;
drop type if exists search_type_enum;
drop type if exists sort_type_enum;
drop type if exists feedback_state_enum;
drop function if exists set_updated_columns;
drop table if exists status_model;
drop function if exists update_parsing_job_status;
drop function if exists clear_collected_objects_if_set_init_status;
drop type if exists status_enum;